[package]
name = "split_merge_hub_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "split_merge_hub_demo"
path = "src/main.rs"

[[bin]]
name = "mock_split_merge_hub"
path = "src/main_mockup.rs"


[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
pretty_env_logger = "0.5"
log = "0.4"
csv = { version = "1.3" }
tempfile = "3.10"
anyhow = "1.0"
