[package]
name = "split_merge_hub_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
rayon = "1.10"
clap = { version = "4.5.40", features = ["derive"] }
pretty_env_logger = "0.5"
log = "0.4"
csv = { version = "1.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.10"
bytes = "1.6"
memmap2 = "0.9"
anyhow = "1.0"
